package utility;
// Generated 23-Mar-2020 5:36:11 PM by Hibernate Tools 4.3.1



/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private int id;
     private String name;

    public Author() {
    }

	
    public Author(int id) {
        this.id = id;
    }
    public Author(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String toString(){
        return "Id is: " + this.id +", Name is: " + this.name;
    }



}


